SET NOCOUNT ON;
ALTER DATABASE CURRENT SET COMPATIBILITY_LEVEL = 170;

IF OBJECT_ID('dbo.Warehouses', 'U') IS NULL CREATE TABLE dbo.Warehouses (WarehouseID INT NOT NULL PRIMARY KEY, WarehouseCode NVARCHAR(30) NOT NULL, WarehouseName NVARCHAR(200) NOT NULL, AddressLine1 NVARCHAR(200) NULL, City NVARCHAR(100) NULL, State NVARCHAR(50) NULL, PostalCode NVARCHAR(20) NULL, Country NVARCHAR(100) NULL, IsActive BIT NOT NULL);
IF OBJECT_ID('dbo.ProductCategories', 'U') IS NULL CREATE TABLE dbo.ProductCategories (CategoryID INT NOT NULL PRIMARY KEY, CategoryCode NVARCHAR(30) NOT NULL, CategoryName NVARCHAR(200) NOT NULL, ParentCategoryID INT NULL, Description NVARCHAR(MAX) NULL, IsActive BIT NOT NULL, CreatedDate DATETIME2 NOT NULL);
IF OBJECT_ID('dbo.ProductCatalog', 'U') IS NULL CREATE TABLE dbo.ProductCatalog (ProductID INT NOT NULL PRIMARY KEY, SKU NVARCHAR(60) NOT NULL, ProductName NVARCHAR(250) NOT NULL, CategoryID INT NOT NULL, Manufacturer NVARCHAR(200) NULL, UnitOfMeasure NVARCHAR(30) NULL, UnitPrice DECIMAL(18,2) NOT NULL, Weight DECIMAL(18,3) NULL, IsActive BIT NOT NULL, CreatedDate DATETIME2 NOT NULL, ModifiedDate DATETIME2 NOT NULL);
IF OBJECT_ID('dbo.ProductDescriptions', 'U') IS NULL CREATE TABLE dbo.ProductDescriptions (ProductDescriptionID INT NOT NULL PRIMARY KEY, ProductID INT NOT NULL, LanguageCode NVARCHAR(20) NOT NULL, ShortDescription NVARCHAR(MAX) NULL, LongDescription NVARCHAR(MAX) NULL, Specifications NVARCHAR(MAX) NULL);
IF OBJECT_ID('dbo.Customers', 'U') IS NULL CREATE TABLE dbo.Customers (CustomerID INT NOT NULL PRIMARY KEY, CustomerCode NVARCHAR(30) NOT NULL, CompanyName NVARCHAR(250) NOT NULL, ContactFirstName NVARCHAR(100) NULL, ContactLastName NVARCHAR(100) NULL, Email NVARCHAR(320) NULL, Phone NVARCHAR(50) NULL, CustomerType NVARCHAR(50) NULL, CreditLimit DECIMAL(18,2) NULL, IsActive BIT NOT NULL, CreatedDate DATETIME2 NOT NULL);
IF OBJECT_ID('dbo.CustomerAddresses', 'U') IS NULL CREATE TABLE dbo.CustomerAddresses (AddressID INT NOT NULL PRIMARY KEY, CustomerID INT NOT NULL, AddressType NVARCHAR(30) NOT NULL, AddressLine1 NVARCHAR(200) NOT NULL, AddressLine2 NVARCHAR(200) NULL, City NVARCHAR(100) NOT NULL, State NVARCHAR(50) NULL, PostalCode NVARCHAR(20) NULL, Country NVARCHAR(100) NULL, IsPrimary BIT NOT NULL);
IF OBJECT_ID('dbo.Inventory', 'U') IS NULL CREATE TABLE dbo.Inventory (InventoryID INT NOT NULL PRIMARY KEY, ProductID INT NOT NULL, WarehouseID INT NOT NULL, QuantityOnHand INT NOT NULL, QuantityReserved INT NOT NULL, QuantityAvailable AS (QuantityOnHand - QuantityReserved) PERSISTED, ReorderLevel INT NOT NULL, ReorderQuantity INT NOT NULL, LastRestockDate DATETIME2 NULL);
IF OBJECT_ID('dbo.Orders', 'U') IS NULL CREATE TABLE dbo.Orders (OrderID INT NOT NULL PRIMARY KEY, OrderNumber NVARCHAR(40) NOT NULL, CustomerID INT NOT NULL, OrderDate DATETIME2 NOT NULL, RequiredDate DATETIME2 NULL, ShippingAddressID INT NULL, BillingAddressID INT NULL, WarehouseID INT NOT NULL, OrderStatus NVARCHAR(40) NOT NULL, SubTotal DECIMAL(18,2) NOT NULL, TaxAmount DECIMAL(18,2) NOT NULL, ShippingAmount DECIMAL(18,2) NOT NULL, TotalAmount DECIMAL(18,2) NOT NULL, CreatedBy NVARCHAR(100) NULL, CreatedDate DATETIME2 NOT NULL, ModifiedDate DATETIME2 NOT NULL);
IF OBJECT_ID('dbo.OrderLines', 'U') IS NULL CREATE TABLE dbo.OrderLines (OrderLineID INT NOT NULL PRIMARY KEY, OrderID INT NOT NULL, LineNumber INT NOT NULL, ProductID INT NOT NULL, WarehouseID INT NOT NULL, Quantity INT NOT NULL, UnitPrice DECIMAL(18,2) NOT NULL, DiscountPercent DECIMAL(9,2) NOT NULL, LineTotal DECIMAL(18,2) NOT NULL);
IF OBJECT_ID('dbo.Shipments', 'U') IS NULL CREATE TABLE dbo.Shipments (ShipmentID INT NOT NULL PRIMARY KEY, ShipmentNumber NVARCHAR(40) NOT NULL, OrderID INT NOT NULL, WarehouseID INT NOT NULL, CarrierName NVARCHAR(100) NULL, TrackingNumber NVARCHAR(100) NULL, ShipmentStatus NVARCHAR(40) NOT NULL, ShippedDate DATETIME2 NULL, EstimatedDeliveryDate DATETIME2 NULL, DeliveredDate DATETIME2 NULL);
IF OBJECT_ID('dbo.SemanticSearchLog', 'U') IS NULL CREATE TABLE dbo.SemanticSearchLog (SemanticSearchLogID INT NOT NULL PRIMARY KEY, QueryText NVARCHAR(MAX) NOT NULL, TopProductID INT NULL, TopProductName NVARCHAR(250) NULL, TopScore DECIMAL(9,4) NULL, ResultCount INT NOT NULL, SearchDate DATETIME2 NOT NULL);

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ProductCatalog_Category') ALTER TABLE dbo.ProductCatalog ADD CONSTRAINT FK_ProductCatalog_Category FOREIGN KEY (CategoryID) REFERENCES dbo.ProductCategories(CategoryID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ProductDescriptions_Product') ALTER TABLE dbo.ProductDescriptions ADD CONSTRAINT FK_ProductDescriptions_Product FOREIGN KEY (ProductID) REFERENCES dbo.ProductCatalog(ProductID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_CustomerAddresses_Customer') ALTER TABLE dbo.CustomerAddresses ADD CONSTRAINT FK_CustomerAddresses_Customer FOREIGN KEY (CustomerID) REFERENCES dbo.Customers(CustomerID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Inventory_Product') ALTER TABLE dbo.Inventory ADD CONSTRAINT FK_Inventory_Product FOREIGN KEY (ProductID) REFERENCES dbo.ProductCatalog(ProductID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Inventory_Warehouse') ALTER TABLE dbo.Inventory ADD CONSTRAINT FK_Inventory_Warehouse FOREIGN KEY (WarehouseID) REFERENCES dbo.Warehouses(WarehouseID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Orders_Customer') ALTER TABLE dbo.Orders ADD CONSTRAINT FK_Orders_Customer FOREIGN KEY (CustomerID) REFERENCES dbo.Customers(CustomerID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Orders_ShippingAddress') ALTER TABLE dbo.Orders ADD CONSTRAINT FK_Orders_ShippingAddress FOREIGN KEY (ShippingAddressID) REFERENCES dbo.CustomerAddresses(AddressID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Orders_BillingAddress') ALTER TABLE dbo.Orders ADD CONSTRAINT FK_Orders_BillingAddress FOREIGN KEY (BillingAddressID) REFERENCES dbo.CustomerAddresses(AddressID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Orders_Warehouse') ALTER TABLE dbo.Orders ADD CONSTRAINT FK_Orders_Warehouse FOREIGN KEY (WarehouseID) REFERENCES dbo.Warehouses(WarehouseID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_OrderLines_Order') ALTER TABLE dbo.OrderLines ADD CONSTRAINT FK_OrderLines_Order FOREIGN KEY (OrderID) REFERENCES dbo.Orders(OrderID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_OrderLines_Product') ALTER TABLE dbo.OrderLines ADD CONSTRAINT FK_OrderLines_Product FOREIGN KEY (ProductID) REFERENCES dbo.ProductCatalog(ProductID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_OrderLines_Warehouse') ALTER TABLE dbo.OrderLines ADD CONSTRAINT FK_OrderLines_Warehouse FOREIGN KEY (WarehouseID) REFERENCES dbo.Warehouses(WarehouseID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Shipments_Order') ALTER TABLE dbo.Shipments ADD CONSTRAINT FK_Shipments_Order FOREIGN KEY (OrderID) REFERENCES dbo.Orders(OrderID);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Shipments_Warehouse') ALTER TABLE dbo.Shipments ADD CONSTRAINT FK_Shipments_Warehouse FOREIGN KEY (WarehouseID) REFERENCES dbo.Warehouses(WarehouseID);
